spring.application.name=instrumentos-tp

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/instrumentos_db
spring.datasource.username=root
spring.datasource.password=1122
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

mercado_pago.access_token= APP_USR-2787025940679290-052118-b9f169bf069b2de91397ac87c1bed529-2442526814
url.ngrok = https://3f47-2803-9800-9841-bad9-ed69-c2a3-afe8-e808.ngrok-free.app